version: '3.8'

networks:
  monitoring:
    driver: bridge

services:
  app:
    container_name: app
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - monitoring    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring  

volumes:
  grafana-data:
  prometheus_data:
